services:
  - type: web
    name: n8n
    env: docker
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://n8n-<ton-service>.onrender.com/  # Remplace <ton-service> par le nom réel


databases:
  - name: n8nDB
    region: frankfurt
    plan: free
